### ISSUE TITLE
Consider releasing it as a npm package?

### ISSUE THREAD

**Issue by LucasIcarus** [zaydek/esbuild-mdx#1]
After painful google stuff, no official esbuild mdx loader or plugin found.

extract code in esbuild.js of this repo, works fine. Consider releasing it?

**Comment by zaydek** [comment]
Hey @LucasIcarus, yeah I also had a painful experience figuring this out, despite the end code being so small.

That’s probably a good idea. Maybe later today I can try. I think I just need to specify peer dependencies, which means users would still need to add `mdx`, `react`, and `react-dom` themselves. Does that seem right to you?

**Comment by zaydek** [comment]
@LucasIcarus Went ahead and implemented this as a plugin as well created a reference repo: https://github.com/zaydek/esbuild-mdx-example.

I’m going to add this to the esbuild community plugins now. Let me know if you have any issues with it.

**Comment by LucasIcarus** [comment]
@zaydek  glad to see..  thks for your code. 

peerDeps seems all right, but the warning message jump out with npm or yarn running is a little bit soft. Some hints within README of new repo will be apperatiated.

**Comment by zaydek** [comment]
Thanks for the note. I added this note to the bottom of the readme: **Note:** `react`, `react-dom`, and `@mdx-js/react` are peer dependencies.

Let me know if you have further feedback!
